# Generated by Django 4.1.3 on 2022-11-26 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('imagen', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('valor', models.IntegerField(verbose_name='Valor')),
                ('fabricacion', models.IntegerField(verbose_name='Año')),
                ('disponibilidad', models.CharField(max_length=20, verbose_name='Disponibilidad')),
                ('categoria', models.CharField(max_length=20, verbose_name='Categoria')),
            ],
        ),
    ]
