# Generated by Django 4.1.3 on 2022-11-26 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compradores',
            fields=[
                ('compradorRut', models.IntegerField(primary_key=True, serialize=False, verbose_name='Rut Comprador')),
                ('compradorNombre', models.CharField(max_length=50, verbose_name='Comprador Nombre')),
                ('compradorApellidoPat', models.CharField(max_length=50, verbose_name='Comprador Apellido Pat')),
                ('compradorApellidoMat', models.CharField(max_length=50, verbose_name='Comprador Apellido Mat')),
                ('compradorTelefono', models.IntegerField(verbose_name='Telefono')),
                ('compradorClave', models.CharField(max_length=100, verbose_name='Contraseña')),
            ],
        ),
        migrations.CreateModel(
            name='Detalles',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedores',
            fields=[
                ('vendedorRut', models.IntegerField(primary_key=True, serialize=False, verbose_name='Rut Vendedor')),
                ('vendedorNombre', models.CharField(max_length=50, verbose_name='Comprador Nombre')),
                ('vendedorApellidoPat', models.CharField(max_length=50, verbose_name='Comprador Vendedor Pat')),
                ('vendedorApellidoMat', models.CharField(max_length=50, verbose_name='Comprador Vendedor Mat')),
                ('vendedorClave', models.CharField(max_length=100, verbose_name='Contraseña')),
            ],
        ),
        migrations.AlterField(
            model_name='auto',
            name='categoria',
            field=models.CharField(max_length=1, verbose_name='Categoria'),
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaventa', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('compradorrut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.compradores')),
                ('id_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.detalles')),
                ('idauto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.auto')),
                ('vendedorrut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.vendedores')),
            ],
        ),
        migrations.AddField(
            model_name='detalles',
            name='autoCod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.auto'),
        ),
    ]
