# Generated by Django 4.1.3 on 2022-11-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0002_compradores_detalles_vendedores_alter_auto_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='categoria',
            field=models.CharField(max_length=20, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='disponibilidad',
            field=models.CharField(max_length=1, verbose_name='Disponibilidad'),
        ),
    ]
